spring:
    profiles:
        active: dev
        include: secret

    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                show_sql: true
                format_sql: true
                use_sql_comments: true